---
title: "EDA Two Sigma Rental"
author: "Samy Soualem"
date: "March 12, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```


# Load packages and data
```{r}
library(jsonlite)
library(purrr)
library(dplyr)
library(ggplot2)
library(caret)
library(Amelia)

source("processing/fct_features.R")


# Load JSON code taken from :
# https://www.kaggle.com/danjordan/two-sigma-connect-rental-listing-inquiries/how-to-correctly-load-data-into-r

DATA_DIR <- "data"

raw_data <-load_data(file.path(DATA_DIR, "train.json"))

head(raw_data, n=1)

#str(raw_data)

# Feature creation / transformation
clean_data <- transform_raw_data(raw_data)

```





## Check top and bottom of data
```{r}
head(clean_data, n = 3)

# Use Rstudio's view option

min(clean_data$created) # "2016-04-01 22:12:41 EST"
max(clean_data$created) # "2016-06-29 21:41:47 EST"
```

## Check your "n"s
```{r}
# Plot # of listings by day
clean_data %>%
  #group_by(yday(created)) %>%
  count(yday(created)) %>%
  plot()
```



# Univariate analysis
## Check missing values
```{r}
sapply(clean_data, function(x) sum(is.na(x)))
sapply(clean_data, function(x) length(unique(x)))

sapply(select(clean_data, contains("price")), function(x) sum(is.nan(x)))


#missmap(clean_data, main = "Missing values vs observed")

# No NA values
```


## Bathrooms
```{r}
count(clean_data, bathrooms)
#table(clean_data$bathrooms, useNA = "always")

clean_data %>%
  group_by(bathrooms) %>%
  summarise (n = n()) %>%
  mutate(pct = n / sum(n) * 100)


ggplot(data=clean_data, aes(x = bathrooms)) +
  geom_bar(stat = "count")
```


## Bedrooms
```{r}
clean_data %>%
  group_by(bedrooms) %>%
  summarise (n = n()) %>%
  mutate(pct = n / sum(n) * 100)

ggplot(data=clean_data, aes(x = bedrooms)) +
  geom_bar(stat = "count")
```

## Price
```{r}
ggplot(data=clean_data, aes(x = factor(0), y = price)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())

summary(clean_data$price)
# Some outliers with huge prices. Too high for rents (max = 4490000)


# boxplot of log(price)
ggplot(data=clean_data, aes(x = factor(0), y = log_price)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())
```

## Features
### Number of features
```{r}
ggplot(data=clean_data, aes(x = factor(0), y = nb_features)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())


clean_data %>%
  group_by(nb_features) %>%
  summarise (n = n()) %>%
  mutate(pct = n / sum(n) * 100)

ggplot(data=clean_data, aes(x = factor(0), y = logp1_nb_features)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())


ggplot(data=clean_data, aes(x = nb_features)) +
  geom_bar(stat = "bin")

ggplot(data=clean_data, aes(x = logp1_nb_features)) +
  geom_bar(stat = "bin")
```

## Description
### Description length (nchar)
```{r}
ggplot(data=clean_data, aes(x = factor(0), y = description_nchar)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())

ggplot(data=clean_data, aes(x = description_nchar)) +
  geom_bar(stat = "bin")

```


## Photos
### Number of photos
```{r}
ggplot(data=clean_data, aes(x = factor(0), y = nb_photos)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())

ggplot(data=clean_data, aes(x = factor(0), y = logp1_nb_photos)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25) + # for whiskers
  # To avoid displaying the dummy x variable
  theme(axis.title.x=element_blank(),
    axis.text.x=element_blank(),
    axis.ticks.x=element_blank())

ggplot(data=clean_data, aes(x = nb_photos)) +
  geom_bar(stat = "bin")

ggplot(data=clean_data, aes(x = logp1_nb_photos)) +
  geom_bar(stat = "bin")
```




# Bivariate analysis
## Creation date
```{r}
# By date
ggplot(data=clean_data, aes(x = created_dt, fill = interest_level)) +
  geom_bar(stat = "count")

# By day of week
ggplot(data=clean_data, aes(x = created_wday, fill = interest_level)) +
  geom_bar(stat = "count")

# By day of month
ggplot(data=clean_data, aes(x = created_mday, fill = interest_level)) +
  geom_bar(stat = "count")

# By month
ggplot(data=clean_data, aes(x = created_month, fill = interest_level)) +
  geom_bar(stat = "count")

# By hour
ggplot(data=clean_data, aes(x = created_hour, fill = interest_level)) +
  geom_bar(stat = "count")
# Most creations at night : timezone problem


```


## Price and simple variants
```{r}
ggplot(data=clean_data, aes(x = interest_level, y = log_price)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers
# Probably important

ggplot(data=clean_data, aes(x = log_price)) +
  geom_bar(stat = "bin")

ggplot(data=clean_data, aes(x = interest_level, y = log_price_per_room_p2)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers

ggplot(data=clean_data, aes(x = log_price_per_room_p2)) +
  geom_bar(stat = "bin")
  
ggplot(data=clean_data, aes(x = interest_level, y = log_price_per_bedroom_p1)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers

ggplot(data=clean_data, aes(x = log_price_per_bedroom_p1)) +
  geom_bar(stat = "bin")

ggplot(data=clean_data, aes(x = interest_level, y = log_price_per_bathroom_p1)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers

ggplot(data=clean_data, aes(x = log_price_per_bathroom_p1)) +
  geom_bar(stat = "bin")

# All price variants probably useful


```

## Bathrooms
```{r}
ggplot(data=clean_data, aes(x = interest_level, y = bathrooms)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers
# No clear signal
```

## Bedrooms
```{r}
ggplot(data=clean_data, aes(x = interest_level, y = bedrooms)) +
  geom_boxplot() +
  stat_boxplot(geom = "errorbar", width = 0.25)  # for whiskers
# No clear signal
```

# Caret feature analysis (to learn about it mostly)
```{r}
plot_sample_size <- 1000
plot_sample <- sample_n(clean_data, plot_sample_size, replace = FALSE)

feat_plot <- select(plot_sample, log_price, nb_photos, nb_features, created_wday)
featurePlot(x = feat_plot
            , y =plot_sample$interest_level
            , plot = "pairs"
            , auto.key = list(columns = 3))

featurePlot(x = feat_plot
            , y =plot_sample$interest_level
            , plot = "box"
            , auto.key = list(columns = 3))


```
